export const CREATE_WISHBOARD = 'CREATE_WISHBOARD';
export const UPDATE_WISHBOARD = 'UPDATE_WISHBOARD';
export const DELETE_WISHBOARD = 'DELETE_WISHBOARD';
export const FETCH_WISHBOARD = 'FETCH_WISHBOARD';